SELECT * FROM ALL_SCHEDULER_RUNNING_JOBS;

SELECT LAST_START_DATE, LAST_RUN_DURATION, LAST_START_DATE+LAST_RUN_DURATION, DBA_SCHEDULER_JOBS.* FROM DBA_SCHEDULER_JOBS where owner='SOPENDW' order by 1 desc;

