git config --global credential.helper wincred

git clone https://github.com/BITSoftware/capi.git
git clone https://github.com/BITSoftware/core-business.git
git clone https://github.com/BITSoftware/core-framework.git
git clone https://github.com/BITSoftware/csec.git
git clone https://github.com/BITSoftware/db.git
git clone https://github.com/BITSoftware/dev.git
git clone https://github.com/BITSoftware/extend.git
git clone https://github.com/BITSoftware/installer.git
git clone https://github.com/BITSoftware/jclient.git
git clone https://github.com/BITSoftware/jclientEar.git
git clone https://github.com/BITSoftware/lib.git
git clone https://github.com/BITSoftware/paer.git
git clone https://github.com/BITSoftware/paur.git
git clone https://github.com/BITSoftware/pavg.git
git clone https://github.com/BITSoftware/pbit.git
git clone https://github.com/BITSoftware/pcsd.git
git clone https://github.com/BITSoftware/pf64.git
git clone https://github.com/BITSoftware/pirw.git
git clone https://github.com/BITSoftware/pmed.git
git clone https://github.com/BITSoftware/prds.git
git clone https://github.com/BITSoftware/prks.git
git clone https://github.com/BITSoftware/reporting.git
git clone https://github.com/BITSoftware/sagr.git
git clone https://github.com/BITSoftware/scld.git
git clone https://github.com/BITSoftware/scqm.git
git clone https://github.com/BITSoftware/scwi.git
git clone https://github.com/BITSoftware/sdei.git
git clone https://github.com/BITSoftware/sdwh.git
git clone https://github.com/BITSoftware/sedi.git
git clone https://github.com/BITSoftware/sele.git
git clone https://github.com/BITSoftware/sems.git
git clone https://github.com/BITSoftware/server.git
git clone https://github.com/BITSoftware/sfhu.git
git clone https://github.com/BITSoftware/sfro.git
git clone https://github.com/BITSoftware/sfxa.git
git clone https://github.com/BITSoftware/sgap.git
git clone https://github.com/BITSoftware/shrmWs.git
git clone https://github.com/BITSoftware/sicm.git
git clone https://github.com/BITSoftware/smag.git
git clone https://github.com/BITSoftware/smlm.git
git clone https://github.com/BITSoftware/smob.git
git clone https://github.com/BITSoftware/smon.git
git clone https://github.com/BITSoftware/smrp.git
git clone https://github.com/BITSoftware/smstr.git
git clone https://github.com/BITSoftware/smstrWS.git
git clone https://github.com/BITSoftware/sobk.git
git clone https://github.com/BITSoftware/soff.git
git clone https://github.com/BITSoftware/sohh.git
git clone https://github.com/BITSoftware/spos.git
git clone https://github.com/BITSoftware/sprc.git
git clone https://github.com/BITSoftware/sprx.git
git clone https://github.com/BITSoftware/srpd.git
git clone https://github.com/BITSoftware/stln.git
git clone https://github.com/BITSoftware/strl.git
git clone https://github.com/BITSoftware/sweb.git
git clone https://github.com/BITSoftware/sweb-themes.git
git clone https://github.com/BITSoftware/swms.git
git clone https://github.com/BITSoftware/swss.git

pause.