-- Create SocrateOpen User
CREATE USER sopen IDENTIFIED BY sopen DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT, DBA, RESOURCE TO sopen WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO sopen WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO sopen WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO sopen WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO sopen WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO sopen WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO sopen;

-- Create SDWH User
CREATE USER sdwh IDENTIFIED BY sdwh DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT, DBA, RESOURCE TO sdwh;
GRANT INSERT ANY TABLE TO sdwh;
GRANT SELECT ANY TABLE TO sdwh;
GRANT EXECUTE ANY PROCEDURE TO sdwh;
GRANT DELETE ANY TABLE TO sdwh;
GRANT UPDATE ANY TABLE TO sdwh;
GRANT UNLIMITED TABLESPACE TO sdwh;