/*** Create triggers to sync table data ***/
DECLARE
    p_sorefSchemaName VARCHAR2(30) := 'SOREFDEV';
    p_targetSchemaName VARCHAR2(30) := 'sodev';
    v_sql VARCHAR2(2000);
BEGIN

        for tableToSync in (
                SELECT UPPER(T.TABLENAME) AS TABLENAME 
                FROM AD_TABLE T 
                    JOIN AD_ENTITYTYPE E ON T.ENTITYTYPE = E.ENTITYTYPE 
                WHERE T.ENTITYTYPE IN(  'C', 'D'
                 , 'SEDI', 'SFLT', 'SHRM', 'SMRP', 'SOBK', 'SOD', 'SOHH', 'SDEI', 'SWSS', 'SELE', 'SBIT', 'SOFF', 'SPOS', 'SMAG'
                 , 'SMST', 'SDWH', 'SWEB', 'SGAP', 'SAGR', 'SFXA', 'SFRO', 'SRPD', 'SMON', 'SCQM'
                 , 'CAPI', 'SMOB', 'SFHU', 'STLN', 'SWMS', 'SEMS', 'SCWI', 'SPRJ', 'SPRC', 'STRL', 'CSEC', 'SDEV', 'SZPM', 'SUMS', 'SMLM', 'SPRV'
                 , 'ITAS', 'SWST', 'SCLD', 'SICM'
                 , 'PAER', 'PF64', 'PRDS', 'PAUR', 'PBIT', 'PMED', 'PAVG', 'PIRW', 'PCSD', 'PDEL', 'PRKS' 
                 , 'XUOM', 'XHRS'
                  ) 
                    AND EXISTS (SELECT * 
                                FROM AD_COLUMN 
                            WHERE UPPER(COLUMNNAME) = 'ENTITYTYPE' 
                            AND AD_COLUMN.AD_TABLE_ID = T.AD_TABLE_ID) 
                    AND UPPER(T.TABLENAME) NOT IN ('AD_ENTITYTYPE', 'SO_DBOBJECT', 'AD_CLIENTCOMPONENT', 'SCQM_TENANTQUOTA') 
                    AND T.ISVIEW = 'N'
                UNION
                SELECT UPPER(TRL.TABLENAME) AS TRL_TABLENAME
                FROM AD_TABLE T 
                    JOIN AD_TABLE TRL ON UPPER(T.TABLENAME) || '_TRL' = UPPER(TRL.TABLENAME) 
                    JOIN AD_ENTITYTYPE E ON T.ENTITYTYPE = E.ENTITYTYPE 
                WHERE T.ENTITYTYPE IN(  'C', 'D'
                 , 'SEDI', 'SFLT', 'SHRM', 'SMRP', 'SOBK', 'SOD', 'SOHH', 'SDEI', 'SWSS', 'SELE', 'SBIT', 'SOFF', 'SPOS', 'SMAG'
                 , 'SMST', 'SDWH', 'SWEB', 'SGAP', 'SAGR', 'SFXA', 'SFRO', 'SRPD', 'SMON', 'SCQM'
                 , 'CAPI', 'SMOB', 'SFHU', 'STLN', 'SWMS', 'SEMS', 'SCWI', 'SPRJ', 'SPRC', 'STRL', 'CSEC', 'SDEV', 'SZPM', 'SUMS', 'SMLM', 'SPRV'
                 , 'ITAS', 'SWST', 'SCLD', 'SICM'
                 , 'PAER', 'PF64', 'PRDS', 'PAUR', 'PBIT', 'PMED', 'PAVG', 'PIRW', 'PCSD', 'PDEL', 'PRKS' 
                 , 'XUOM', 'XHRS'
                  ) 
                    AND EXISTS (SELECT * 
                                FROM AD_COLUMN 
                            WHERE UPPER(COLUMNNAME) = 'ENTITYTYPE' 
                            AND AD_COLUMN.AD_TABLE_ID = T.AD_TABLE_ID) 
                    AND UPPER(T.TABLENAME) NOT IN ('AD_ENTITYTYPE', 'SO_DBOBJECT', 'AD_CLIENTCOMPONENT', 'SCQM_TENANTQUOTA') 
                    AND T.ISVIEW = 'N'
                UNION
                SELECT N'AD_ENTITYTYPE' FROM DUAL
                UNION
                SELECT N'AD_IMPFORMAT' FROM DUAL
                UNION
                SELECT N'AD_IMPFORMAT_ROW' FROM DUAL
                UNION
                SELECT N'AD_MIGRATIONSTEP' FROM DUAL
                UNION
                SELECT N'AD_PRINTCOLOR' FROM DUAL
                UNION
                SELECT N'AD_PRINTFONT' FROM DUAL
                UNION
                SELECT N'AD_PRINTFORM' FROM DUAL
                UNION
                SELECT N'AD_PRINTFORMAT' FROM DUAL
                UNION
                SELECT N'AD_PRINTFORMAT_TRL' FROM DUAL
                UNION
                SELECT N'AD_PRINTFORMATITEM' FROM DUAL
                UNION
                SELECT N'AD_PRINTFORMATITEM_TRL' FROM DUAL
                UNION
                SELECT N'AD_PRINTGRAPH' FROM DUAL
                UNION
                SELECT N'AD_PRINTPAPER' FROM DUAL
                UNION
                SELECT N'AD_PRINTTABLEFORMAT' FROM DUAL
                UNION
                SELECT N'AD_REPORTVIEW_COL' FROM DUAL
                UNION
                SELECT N'AD_SCHEDULE' FROM DUAL
                UNION
                SELECT N'AD_SCHEDULER' FROM DUAL
                UNION
                SELECT N'AD_SCHEDULER_PARA' FROM DUAL
                UNION
                SELECT N'AD_TABLEINDEX' FROM DUAL
                UNION
                SELECT N'AD_WF_BLOCK' FROM DUAL
                UNION
                SELECT N'C_DOCTYPE' FROM DUAL
                UNION
                SELECT N'C_DOCTYPE_TRL' FROM DUAL
                UNION
                SELECT N'AD_TREE' FROM DUAL
                UNION
                SELECT N'AD_TREENODE' FROM DUAL
                UNION
                SELECT N'C_ELEMENTBASE' FROM DUAL
                UNION
                SELECT N'C_ELEMENTVALUEBASE' FROM DUAL
                UNION
                SELECT N'AD_FORMPROCESS' FROM DUAL
                UNION
                SELECT N'C_ACCOUNTGROUP' FROM DUAL
                UNION
                SELECT N'C_ACCOUNTGROUP_TRL' FROM DUAL
                UNION
                SELECT N'GL_CATEGORY_TMPL' FROM DUAL
                UNION
                SELECT N'GL_CATEGORY_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'C_DOCTYPE_TMPL' FROM DUAL
                UNION
                SELECT N'C_DOCTYPE_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'C_NONBUSINESSDAY_TMPL' FROM DUAL
                UNION
                SELECT N'AD_ORGTYPE_TMPL' FROM DUAL
                UNION
                SELECT N'AD_ORGTYPE_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'C_TAXCATEGORY_TMPL' FROM DUAL
                UNION
                SELECT N'C_TAXCATEGORY_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'C_TAX_TMPL' FROM DUAL
                UNION
                SELECT N'C_TAX_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'SO_TAXCOLUMNSET_TMPL' FROM DUAL
                UNION
                SELECT N'SO_TAXCOLUMN_TMPL' FROM DUAL
                UNION
                SELECT N'PA_REPORTLINESET_TMPL' FROM DUAL
                UNION
                SELECT N'PA_REPORTLINE_TMPL' FROM DUAL
                UNION
                SELECT N'PA_REPORTSOURCE_TMPL' FROM DUAL
                UNION
                SELECT N'PA_REPORTCOLUMNSET_TMPL' FROM DUAL
                UNION
                SELECT N'PA_REPORTCOLUMN_TMPL' FROM DUAL
                UNION
                SELECT N'PA_REPORT_TMPL' FROM DUAL
                UNION
                SELECT N'A_ASSET_GROUP_TMPL' FROM DUAL
                UNION
                SELECT N'A_ASSET_GROUP_ACCT_TMPL' FROM DUAL
                UNION
                SELECT N'C_CHARGE_TMPL' FROM DUAL
                UNION
                SELECT N'C_CHARGE_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'C_CHARGE_ACCT_TMPL' FROM DUAL
                UNION
                SELECT N'M_PRODUCT_CATEGORY_TMPL' FROM DUAL
                UNION
                SELECT N'M_PRODUCT_CATEGORY_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'M_PRODUCT_TMPL' FROM DUAL
                UNION
                SELECT N'M_PRODUCT_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'M_PRODUCT_ACCT_TMPL' FROM DUAL
                UNION
                SELECT N'C_PAYMENTMODE_TMPL' FROM DUAL
                UNION
                SELECT N'C_PAYMENTTERM_TMPL' FROM DUAL
                UNION
                SELECT N'C_PAYMENTTERM_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'C_BP_GROUP_TMPL' FROM DUAL
                UNION
                SELECT N'C_BP_GROUP_TMPL_TRL' FROM DUAL
                UNION
                SELECT N'C_BP_GROUP_ACCT_TMPL' FROM DUAL
            )
    LOOP
        BEGIN
            SC_Sync_Dictionary.create_table_trigger(p_table_name => tableToSync.TABLENAME, p_database_link_name => null, p_schema_name => p_targetSchemaName);
        EXCEPTION
            WHEN OTHERS THEN
                raise_application_error (-20001, 'CREATE TRIGGER FOR ' || tableToSync.TABLENAME || ' failed: ' || SQLERRM);
        END;
    END LOOP;
END;

/*** Create trigger to sync DDL ***/
DECLARE
    p_sorefSchemaName VARCHAR2(30) := 'SOREFDEV';
    p_targetSchemaName VARCHAR2(30) := 'sodev';
    v_sql VARCHAR2(2000);
BEGIN
    
    BEGIN
        SC_Sync_Dictionary.create_database_trigger(p_audited_schema_name => p_sorefSchemaName, p_database_link_name => null, p_schema_name => p_TargetSchemaName);
    EXCEPTION
        WHEN OTHERS THEN
            raise_application_error (-20001, 'CREATE DDL trigger failed: ' || SQLERRM);
    END;
END;


/* Drop created triggers */

/*

--Drop triggers to sync table data
BEGIN
    for object in (SELECT Object_Name FROM user_objects where Object_type='TRIGGER' AND 
        Object_NAME like 'TSC_%')
    loop
        execute immediate 'DROP TRIGGER ' || object.Object_Name;
    end loop;
END;
/
--Drop trigger to sync DDL
BEGIN
    execute immediate 'DROP TRIGGER TRG_SYNC_WITH_DEV';
END;

--Drop sql executor
DECLARE
    p_targetSchemaName VARCHAR2(30) := 'sodev';
    v_cnt NUMBER;
    v_sql CLOB;
BEGIN
		v_sql := 'SELECT COUNT(*) FROM all_sequences WHERE Sequence_Owner = '''||upper(p_targetSchemaName)||''' AND Sequence_Name = ''SC_SYNC_LOG_SEQ''';
	    EXECUTE IMMEDIATE v_sql INTO v_cnt;

	    IF v_cnt > 0 THEN
		    v_sql   := 'DROP SEQUENCE '||p_targetSchemaName||'.SC_SYNC_LOG_SEQ';
		    EXECUTE IMMEDIATE v_sql;
	    END IF;

		v_sql := 'SELECT COUNT(*) FROM all_tables WHERE Owner = '''||upper(p_targetSchemaName)||''' AND Table_Name = ''SC_SYNC_LOG''';
	    EXECUTE IMMEDIATE v_sql INTO v_cnt;

	    IF v_cnt > 0 THEN
		    v_sql   := 'DROP TABLE '||p_targetSchemaName||'.SC_SYNC_LOG';
		    EXECUTE IMMEDIATE v_sql;
	    END IF;
END;

--Disable triggers to sync table data
BEGIN
    for object in (SELECT Object_Name FROM user_objects where Object_type='TRIGGER' AND 
        Object_NAME like 'TSC_%')
    loop
        execute immediate 'ALTER TRIGGER ' || object.Object_Name || ' DISABLE';
    end loop;
END;
/
--Disable trigger to sync DDL
BEGIN
    execute immediate 'ALTER TRIGGER TRG_SYNC_WITH_DEV DISABLE';
END;

--Enable triggers to sync table data
BEGIN
    for object in (SELECT Object_Name FROM user_objects where Object_type='TRIGGER' AND 
        Object_NAME like 'TSC_%')
    loop
        execute immediate 'ALTER TRIGGER ' || object.Object_Name || ' ENABLE';
    end loop;
END;
/
--Enable trigger to sync DDL
BEGIN
    execute immediate 'ALTER TRIGGER TRG_SYNC_WITH_DEV ENABLE';
END;
*/

/*** Test create SQL executor ***/
DECLARE
    p_targetSchemaName VARCHAR2(30) := 'sodev';
BEGIN
    
    BEGIN
        SC_Sync_Dictionary.create_sql_executor(p_schema_name => p_TargetSchemaName);
    EXCEPTION
        WHEN OTHERS THEN
            raise_application_error (-20001, 'CREATE SQL Executor failed: ' || SQLERRM);
    END;
END;

/*** Get Entity types to be inserted in target schema that are not migrated ***/
select e.* from AD_EntityType e
left join sodev.AD_EntityType s on s.EntityType = e.EntityType
where s.EntityType is null;

REM INSERTING into AD_ENTITYTYPE
SET DEFINE OFF;
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SMAG','0','0','2140900014','Y',to_date('17-01-2011 16:05:52','DD-MM-RRRR HH24:MI:SS'),'0',to_date('18-10-2013 16:48:47','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Magento Integration','Integration component with Magento E-Commerce suite',null,'1.0','org.bitsoftware.smag.model','smag.jar','N','N',null,null,'N','3.6.0',null,'org.bitsoftware.smag.model.SMAGModelValidator','100',null,'Y');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SDWH','0','0','2140900016','Y',to_date('15-02-2011 13:10:45','DD-MM-RRRR HH24:MI:SS'),'0',to_date('18-10-2013 16:47:08','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Data Warehouse','SocrateCloud Data Warehouse Component',null,'1.0','org.bitsoftware.sdwh.model','sdwh.jar','N','N',null,null,'N',null,null,null,'100','SOPENDW','Y');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SUMS','0','0','2140900046','Y',to_date('29-09-2014 15:19:50','DD-MM-RRRR HH24:MI:SS'),'0',to_date('29-09-2014 15:19:50','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud User Management','SocrateCloud User Management',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('CAST','0','0','2140900053','Y',to_date('06-04-2015 12:43:01','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 12:43:01','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud CustAssets',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('ECOT','0','0','2140900056','Y',to_date('06-04-2015 13:10:51','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:10:51','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud EcoTax',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('EXCI','0','0','2140900057','Y',to_date('06-04-2015 13:12:54','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:12:54','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Excise','Componenta "EXCISE" pentru ERP',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SRES','0','0','2140900061','Y',to_date('06-04-2015 13:38:01','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:38:01','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Resource',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('MTLG','0','0','2140900071','Y',to_date('07-04-2015 14:31:08','DD-MM-RRRR HH24:MI:SS'),'0',to_date('07-04-2015 14:31:08','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud MultiLang',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('DVIE','0','0','2140900072','Y',to_date('07-04-2015 14:32:33','DD-MM-RRRR HH24:MI:SS'),'0',to_date('07-04-2015 14:32:33','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Custom Taxes',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('STRZ','0','0','2140900080','Y',to_date('02-07-2015 13:00:03','DD-MM-RRRR HH24:MI:SS'),'0',to_date('02-07-2015 13:00:03','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Treasury',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SMKT','0','0','2140900082','Y',to_date('09-07-2015 14:48:54','DD-MM-RRRR HH24:MI:SS'),'0',to_date('09-07-2015 14:48:54','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Campaign',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('CSTA','0','0','2140900051','Y',to_date('10-03-2015 13:47:44','DD-MM-RRRR HH24:MI:SS'),'0',to_date('10-03-2015 13:47:44','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Starter','Componenta "Starter" pentru ERP',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('BATL','0','0','2140900064','Y',to_date('06-04-2015 13:47:27','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:47:27','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud BatchLot',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('PRCH','0','0','2140900069','Y',to_date('07-04-2015 14:24:34','DD-MM-RRRR HH24:MI:SS'),'0',to_date('07-04-2015 14:25:10','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Purchase',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SUOM','0','0','2140900070','Y',to_date('07-04-2015 14:26:50','DD-MM-RRRR HH24:MI:SS'),'0',to_date('07-04-2015 14:26:50','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud UOM Conversion',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('RPL0','0','0','2140900076','Y',to_date('21-04-2015 12:26:11','DD-MM-RRRR HH24:MI:SS'),'0',to_date('28-04-2015 15:23:23','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Replanish bază','Funcționalitate de bază Replanish: Stoc Min, Max, tab Aprovizionare și raport, calcul Reaprovizionare',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('LEAD','0','0','2140900078','Y',to_date('30-04-2015 12:28:08','DD-MM-RRRR HH24:MI:SS'),'0',to_date('30-04-2015 12:28:08','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Lead','Componenta ce include funcționalitățile aferente Lead Management',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SCTR','0','0','2140900083','Y',to_date('09-07-2015 15:00:09','DD-MM-RRRR HH24:MI:SS'),'0',to_date('09-07-2015 15:00:09','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Contracte',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('WMS1','0','0','2140900059','Y',to_date('06-04-2015 13:31:04','DD-MM-RRRR HH24:MI:SS'),'0',to_date('28-04-2015 14:21:59','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud WMS1','Componenta "WMS" pentru ERP',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SBOM','0','0','2140900060','Y',to_date('06-04-2015 13:32:18','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:32:18','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud BOM',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('PRCE','0','0','2140900065','Y',to_date('06-04-2015 13:52:59','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:52:59','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Price Standard',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('PR10','0','0','2140900066','Y',to_date('06-04-2015 14:05:28','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 14:05:28','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Price Simulator',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('PRSB','0','0','2140900067','Y',to_date('07-04-2015 14:20:14','DD-MM-RRRR HH24:MI:SS'),'0',to_date('07-04-2015 14:20:14','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Product Substitute',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SBDL','0','0','2140900073','Y',to_date('07-04-2015 14:33:54','DD-MM-RRRR HH24:MI:SS'),'0',to_date('07-04-2015 14:33:54','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud BoxDelivery',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('ACCT','0','0','2140900074','Y',to_date('09-04-2015 07:56:46','DD-MM-RRRR HH24:MI:SS'),'0',to_date('09-04-2015 07:56:46','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Accounting',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('RPL2','0','0','2140900075','Y',to_date('09-04-2015 08:09:45','DD-MM-RRRR HH24:MI:SS'),'0',to_date('09-04-2015 08:09:45','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Replanish Retail','replanish retail - cu calcul direct pt fz si pt intern',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('INVE','0','0','2140900054','Y',to_date('06-04-2015 12:47:27','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 12:47:27','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Inventory','Componenta "Inventory" pentru ERP',null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SALE','0','0','2140900052','Y',to_date('06-04-2015 12:18:01','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 12:18:01','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Sales',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('DPAY','0','0','2140900055','Y',to_date('06-04-2015 13:04:59','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:04:59','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Dpay2',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SPKG','0','0','2140900062','Y',to_date('06-04-2015 13:40:16','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:40:16','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Packaging',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SABO','0','0','2140900063','Y',to_date('06-04-2015 13:43:06','DD-MM-RRRR HH24:MI:SS'),'0',to_date('06-04-2015 13:43:06','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Abonamente',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('PRRL','0','0','2140900068','Y',to_date('07-04-2015 14:20:46','DD-MM-RRRR HH24:MI:SS'),'0',to_date('07-04-2015 14:20:46','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Product Related',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SONP','0','0','2140900077','Y',to_date('29-04-2015 14:59:44','DD-MM-RRRR HH24:MI:SS'),'0',to_date('29-04-2015 14:59:44','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud OnPremise',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
Insert into AD_ENTITYTYPE (ENTITYTYPE,AD_CLIENT_ID,AD_ORG_ID,AD_ENTITYTYPE_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,HELP,VERSION,MODELPACKAGE,CLASSPATH,PROCESSING,CREATECOMPONENT,RECORD_ID,SUMMARY,ISREGISTERED,REQUIRECOMPIEREVERSION,REQUIRECOMPONENTVERSION,MODELVALIDATIONCLASSES,RELATIVELOADNO,DBSCHEMAUSER,ISREQUIRETENANTLINK) values ('SREQ','0','0','2140900084','Y',to_date('10-07-2015 13:04:57','DD-MM-RRRR HH24:MI:SS'),'0',to_date('10-07-2015 13:04:57','DD-MM-RRRR HH24:MI:SS'),'0','SocrateCloud Request',null,null,null,null,null,'N','N',null,null,'N',null,null,null,null,null,'N');
