/*******************************
 * Select printformats to Export from SourceDB
 ********************************/
 
--drop table T_PF_ID;
CREATE TABLE T_PF_ID(AD_PRINTFORMAT_ID NUMBER(10,0) NOT NULL);

BEGIN
  INSERT INTO T_PF_ID(AD_PrintFormat_ID)
  SELECT pf.AD_PrintFormat_ID
  FROM AD_PrintFormat pf
  where pf.AD_Client_ID=0
    and pf.ISFORM='Y'
    and pf.Name like '%_STD';
    
  WHILE SQL%ROWCOUNT > 0
  LOOP
    INSERT INTO T_PF_ID(AD_PrintFormat_ID)
    SELECT DISTINCT pfi.AD_PrintFormatChild_ID
    FROM AD_PrintFormatItem pfi
    JOIN T_PF_ID tmp ON tmp.AD_PRINTFORMAT_ID=pfi.AD_PrintFormat_ID
    WHERE pfi.AD_PrintFormatChild_ID IS NOT NULL
      AND NOT EXISTS(SELECT * from T_PF_ID tmp1 where tmp1.AD_PrintFormat_ID=pfi.AD_PrintFormatChild_ID);
  END LOOP;
END;

--Print formats to copy
SELECT pf.* FROM AD_PrintFormat pf
join T_PF_ID tmp on tmp.AD_PRINTFORMAT_ID=pf.AD_PrintFormat_ID
WHERE tmp.AD_PrintFormat_ID >=1000000 
  AND tmp.AD_PrintFormat_ID<2140000000
;

--Print formats TRL to copy
SELECT trl.* FROM AD_PrintFormat_TRL trl
join T_PF_ID tmp on tmp.AD_PRINTFORMAT_ID=trl.AD_PrintFormat_ID
where trl.AD_Language='ro_RO'
  AND tmp.AD_PrintFormat_ID >=1000000 
  AND tmp.AD_PrintFormat_ID<2140000000
;

--Print format items to copy
SELECT pfi.* FROM AD_PrintFormatItem pfi
join T_PF_ID tmp on tmp.AD_PRINTFORMAT_ID=pfi.AD_PrintFormat_ID
where pfi.AD_PrintFormatItem_ID >=1000000 
  AND pfi.AD_PrintFormatItem_ID<2140000000
;

--Print format items trl to copy
SELECT trl.* FROM AD_PrintFormatItem pfi
join T_PF_ID tmp on tmp.AD_PRINTFORMAT_ID=pfi.AD_PrintFormat_ID
join AD_PrintFormatItem_TRL trl on pfi.AD_PrintFormatItem_ID = trl.AD_PrintFormatItem_ID AND trl.AD_Language='ro_RO'
where pfi.AD_PrintFormatItem_ID >=1000000 
  AND pfi.AD_PrintFormatItem_ID<2140000000
;




/*******************************
 * Insert Exported print formats into target DB
 ********************************/

--Source printformats
CREATE TABLE AD_PRINTFORMAT1
AS
SELECT *
  FROM AD_PRINTFORMAT
  WHERE 1=0;

--Source printformats trl
CREATE TABLE AD_PRINTFORMAT1_TRL
AS
SELECT *
  FROM AD_PRINTFORMAT_TRL
  WHERE 1=0;
  
--Source printformatitems
CREATE TABLE AD_PRINTFORMATITEM1
AS
SELECT *
  FROM AD_PRINTFORMATITEM
  WHERE 1=0;

--Source printformatitems trl
CREATE TABLE AD_PRINTFORMATITEM1_TRL
AS
SELECT *
  FROM AD_PRINTFORMATITEM_TRL
  WHERE 1=0;


ALTER TABLE AD_PRINTFORMAT1 ADD CONSTRAINT PK_AD_PRINTFORMAT1 PRIMARY KEY (AD_PRINTFORMAT_ID);
ALTER TABLE AD_PRINTFORMAT1_TRL ADD CONSTRAINT PK_AD_PRINTFORMAT1_TRL PRIMARY KEY (AD_LANGUAGE, AD_PRINTFORMAT_ID);
ALTER TABLE AD_PRINTFORMATITEM1 ADD CONSTRAINT PK_AD_PRINTFORMATITEM1 PRIMARY KEY (AD_PRINTFORMATITEM_ID);
ALTER TABLE AD_PRINTFORMATITEM1_TRL ADD CONSTRAINT PK_AD_PRINTFORMATITEM1_TRL PRIMARY KEY (AD_LANGUAGE, AD_PRINTFORMATITEM_ID);

ALTER TABLE AD_PRINTFORMAT1_TRL ADD CONSTRAINT FK_AD_PRINTFORMAT1 FOREIGN KEY (AD_PRINTFORMAT_ID) REFERENCES AD_PRINTFORMAT1(AD_PRINTFORMAT_ID);
ALTER TABLE AD_PRINTFORMATITEM1 ADD CONSTRAINT FK_AD_PRINTFORMAT1_1 FOREIGN KEY (AD_PRINTFORMAT_ID) REFERENCES AD_PRINTFORMAT1(AD_PRINTFORMAT_ID);
ALTER TABLE AD_PRINTFORMATITEM1_TRL ADD CONSTRAINT FK_AD_PRINTFORMATITEM1 FOREIGN KEY (AD_PRINTFORMATITEM_ID) REFERENCES AD_PRINTFORMATITEM1(AD_PRINTFORMATITEM_ID);

--insert data from export in previous created tables
/*
INSERT INTO AD_PRINTFORMAT1 ...
INSERT INTO AD_PRINTFORMAT1_TRL ...
INSERT INTO AD_PRINTFORMATITEM1 ...
INSERT INTO AD_PRINTFORMATITEM1_TRL ...
*/

--create temporary table to map old IDs to New IDs
CREATE TABLE T_AD_PRINTFORMAT_ID(Old_ID NUMBER(10,0) NOT NULL, New_ID NUMBER(10,0));
CREATE TABLE T_AD_PRINTFORMATITEM_ID(Old_ID NUMBER(10,0) NOT NULL, New_ID NUMBER(10,0));

--insert old IDs into previously created temporary tables
INSERT INTO T_AD_PRINTFORMAT_ID(Old_ID)
SELECT AD_PRINTFORMAT_ID
FROM AD_PrintFormat1;

INSERT INTO T_AD_PRINTFORMATITEM_ID(Old_ID)
SELECT AD_PRINTFORMATITEM_ID
FROM AD_PrintFormatItem1;

--get new IDs for Print formats
DECLARE
  CURSOR oldIDs IS
    SELECT t.Old_ID
    FROM T_AD_PRINTFORMAT_ID t
    ORDER BY t.Old_ID;
      
  v_AD_Sequence_ID NUMBER;
  v_New_ID NUMBER;  

BEGIN
  SELECT AD_Sequence_ID 
  INTO v_AD_Sequence_ID
  FROM AD_Sequence 
  WHERE Name='AD_PrintFormat'
    AND IsTableID='Y';

  FOR oldID IN oldIDs
  LOOP 
    nextIDSO(v_AD_Sequence_ID, 'N', 'Y', v_New_ID);
    
    UPDATE T_AD_PRINTFORMAT_ID SET New_ID=v_New_ID WHERE Old_ID=oldID.Old_ID;
  END LOOP;
END;
        
--get new IDs for Print formats Items
DECLARE
  CURSOR oldIDs IS
    SELECT t.Old_ID
    FROM T_AD_PRINTFORMATITEM_ID t
    ORDER BY t.Old_ID;
      
  v_AD_Sequence_ID NUMBER;
  v_New_ID NUMBER;  

BEGIN
  SELECT AD_Sequence_ID 
  INTO v_AD_Sequence_ID
  FROM AD_Sequence 
  WHERE Name='AD_PrintFormatItem'
    AND IsTableID='Y';

  FOR oldID IN oldIDs
  LOOP 
    nextIDSO(v_AD_Sequence_ID, 'N', 'Y', v_New_ID);
    
    UPDATE T_AD_PRINTFORMATITEM_ID SET New_ID=v_New_ID WHERE Old_ID=oldID.Old_ID;
  END LOOP;
END;

--replace old IDs with new ids
ALTER TABLE AD_PRINTFORMAT1_TRL DISABLE CONSTRAINT FK_AD_PRINTFORMAT1;
ALTER TABLE AD_PRINTFORMATITEM1 DISABLE CONSTRAINT FK_AD_PRINTFORMAT1_1;
ALTER TABLE AD_PRINTFORMATITEM1_TRL DISABLE CONSTRAINT FK_AD_PRINTFORMATITEM1;

UPDATE AD_PRINTFORMAT1 set AD_PRINTFORMAT_ID = (SELECT New_ID FROM T_AD_PRINTFORMAT_ID WHERE Old_ID=AD_PRINTFORMAT_ID);
UPDATE AD_PRINTFORMAT1_TRL set AD_PRINTFORMAT_ID = (SELECT New_ID FROM T_AD_PRINTFORMAT_ID WHERE Old_ID=AD_PRINTFORMAT_ID);
UPDATE AD_PRINTFORMATITEM1 set AD_PRINTFORMAT_ID = (SELECT New_ID FROM T_AD_PRINTFORMAT_ID WHERE Old_ID=AD_PRINTFORMAT_ID),
  AD_PRINTFORMATITEM_ID = (SELECT New_ID FROM T_AD_PRINTFORMATITEM_ID WHERE Old_ID=AD_PRINTFORMATITEM_ID);
UPDATE AD_PRINTFORMATITEM1_TRL set AD_PRINTFORMATITEM_ID = (SELECT New_ID FROM T_AD_PRINTFORMATITEM_ID WHERE Old_ID=AD_PRINTFORMATITEM_ID);

UPDATE AD_PRINTFORMATITEM1 set AD_PRINTFORMATCHILD_ID = (SELECT New_ID FROM T_AD_PRINTFORMAT_ID WHERE Old_ID=AD_PRINTFORMATCHILD_ID)
WHERE AD_PRINTFORMATCHILD_ID >=1000000
  AND AD_PRINTFORMATCHILD_ID < 2140000000;

ALTER TABLE AD_PRINTFORMAT1_TRL ENABLE CONSTRAINT FK_AD_PRINTFORMAT1;
ALTER TABLE AD_PRINTFORMATITEM1 ENABLE CONSTRAINT FK_AD_PRINTFORMAT1_1;
ALTER TABLE AD_PRINTFORMATITEM1_TRL ENABLE CONSTRAINT FK_AD_PRINTFORMATITEM1;

--reset other columns
UPDATE AD_PRINTFORMAT1 set AD_Client_ID=0, AD_Org_ID=0, Created=sysdate, CreatedBy=0, Updated=sysdate, UpdatedBy=0;
UPDATE AD_PRINTFORMAT1_TRL set AD_Client_ID=0, AD_Org_ID=0, Created=sysdate, CreatedBy=0, Updated=sysdate, UpdatedBy=0;
UPDATE AD_PRINTFORMATITEM1 set AD_Client_ID=0, AD_Org_ID=0, Created=sysdate, CreatedBy=0, Updated=sysdate, UpdatedBy=0;
UPDATE AD_PRINTFORMATITEM1_TRL set AD_Client_ID=0, AD_Org_ID=0, Created=sysdate, CreatedBy=0, Updated=sysdate, UpdatedBy=0;

--update print paper
UPDATE AD_PRINTFORMAT1 set AD_PrintPaper_ID=103 WHERE AD_PrintPaper_ID IN (1000007, 1000005);

--update print table format
UPDATE AD_PRINTFORMAT1 set AD_PrintTableFormat_ID=100 WHERE AD_PrintTableFormat_ID>=1000000 AND AD_PrintTableFormat_ID<2140000000;

--export data from table to be inserted in target tables
select * from AD_PrintFormat1;
select * from AD_PrintFormat1_TRL;
select * from AD_PrintFormatItem1;
select * from AD_PrintFormatItem1_TRL;